const SAVE_TODO = 'SAVE_TODO';
const DELETE_TODO = 'DELETE_TODO';
const TOGGLE_TODO = 'TOGGLE_TODO';
const EDIT_TODO = 'EDIT_TODO';

export default {
  SAVE_TODO,
  DELETE_TODO,
  TOGGLE_TODO,
  EDIT_TODO,
};
