// @flow

const REGISTER_MODAL = 'REGISTER_MODAL';
const TOGGLE_MODAL = 'REGISTER_MODAL';

const EDIT_TODO_MODAL = 'EDIT_TODO_MODAL';

export default {
  REGISTER_MODAL,
  EDIT_TODO_MODAL,
  TOGGLE_MODAL,
};
